# Production environment overrides
services:
  backend:
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - DB_SSL=false # Set to 'true' only when using cloud databases with SSL (AWS RDS, Heroku, Azure)
    restart: always

  frontend:
    restart: always

  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: [] # Don't expose port in production
    restart: always
